---
- name: install nginx web server
  hosts: web
  tasks:
    - name: install nginx package
      apt: 
        update_cache: yes
        name: nginx
    - name: start nginx
      command: service nginx restart
    - name: Copy file with owner and permissions
      copy:
        # src: ./index.html
        content: "<h1>Your Wonderful!</h1>"
        dest: /var/www/html/index.html
        owner: www-data
        group: www-data
        mode: '0777'